import "./globals.css";
import type { Metadata } from "next";
import type { JSX, ReactNode } from "react";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "CHAT",
  description: "Generated by ARNNVV",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <Navbar />
        {children}
        <Toaster richColors={true} />
      </body>
    </html>
  );
}
